name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install MinGW cross-compiler on Linux
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install -y mingw-w64

    - name: Build on Linux (amd64-linux-gcc)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-linux-gcc
        CC: gcc
        MAKE: make
      shell: bash
      run: ./bin/ci-build.sh

    - name: Build on Linux (amd64-linux-clang)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-linux-clang
        CC: clang
        MAKE: make
      shell: bash
      run: ./bin/ci-build.sh

    - name: Build on Linux (amd64-windows-mingw)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-windows-mingw
        CC: x86_64-w64-mingw32-gcc
        MAKE: make
      shell: bash
      run: ./bin/ci-build.sh

    - name: Build on macOS (amd64-macosx-clang)
      if: runner.os == 'macOS'
      env:
        PREFIX: amd64-macosx
        CC: clang
        MAKE: make
      shell: bash
      run: |
        # coreutils required for realpath
        brew install coreutils tree
        ./bin/ci-build.sh

    - name: Build on macOS (amd64-freebsd-gcc)
      if: runner.os == 'macOS'
      env:
        PREFIX: amd64-freebsd-gcc
        CC: gcc
        MAKE: gmake
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'PREFIX CC MAKE'
        usesh: true
        prepare: pkg install -y tree zip gmake lang/gcc
        run: ./bin/ci-build.sh

    - name: Upload artifacts built on Linux
      uses: actions/upload-artifact@v3
      with:
        path: ./*.zip
        if-no-files-found: error
        retention-days: 5

    # - name: Release (publish build artifacts)
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: *.zip
