name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build (Linux - gcc/clang)
      if: runner.os == 'Linux'
      run: |
        ./configure --prefix=build
        # gcc
        export CC=gcc
        make lib
        sudo cp build/Linux/rel/cc/lib/libzsv.a /usr/local/lib/
        make install
        # clang
        export CC=clang
        make lib
        sudo cp build/Linux/rel/cc/lib/libzsv.a /usr/local/lib/
        make install

    # - name: Build (macOS - clang)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew install coreutils
    #     ./configure --prefix=build
    #     export CC=clang
    #     make lib
    #     sudo cp build/Linux/rel/cc/lib/libzsv.a /usr/local/lib/
    #     make install
