name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build (amd64-linux-gcc)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-linux-gcc
        CC: gcc
        MAKE: make
      shell: bash
      run: ./bin/ci-build.sh

    - name: Build (amd64-linux-clang)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-linux-clang
        CC: clang
        MAKE: make
      shell: bash
      run: ./bin/ci-build.sh

    - name: Build (amd64-windows)
      if: runner.os == 'Linux'
      env:
        PREFIX: amd64-windows
        CC: x86_64-w64-mingw32-gcc
        MAKE: make
      shell: bash
      run: |
        sudo apt install -y mingw-w64
        ./bin/ci-build.sh

    - name: Build (amd64-macosx-clang)
      if: runner.os == 'macOS'
      env:
        PREFIX: amd64-macosx
        CC: clang
        MAKE: make
      shell: bash
      run: |
        # coreutils required for realpath
        brew install coreutils tree
        ./bin/ci-build.sh

    - name: Build (amd64-freebsd-gcc)
      if: runner.os == 'macOS'
      env:
        PREFIX: amd64-freebsd-gcc
        CC: gcc
        MAKE: gmake
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'PREFIX CC MAKE'
        usesh: true
        prepare: pkg install -y tree zip gmake lang/gcc
        run: ./bin/ci-build.sh
