name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PREFIX: build

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: ./configure --prefix=$PREFIX

    - name: Build (Linux - gcc and clang)
      if: runner.os == 'Linux'
      run: |
        # gcc
        echo "Building with gcc"
        gcc --version
        CC=gcc make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with gcc successfully!"
        # clang
        rm -rf $PREFIX
        echo "Building with clang"
        clang --version
        CC=clang make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"

    - name: Build (macOS - clang)
      if: runner.os == 'macOS'
      run: |
        # coreutils required for realpath
        brew install coreutils
        echo "Building with clang"
        clang --version
        CC=clang make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"
