name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    branches: [main]
    types: [created]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      AMD64_LINUX_GCC: zsv-amd64-linux-gcc
      AMD64_LINUX_CLANG: zsv-amd64-linux-clang
      AMD64_WINDOWS_MINGW: zsv-amd64-windows-mingw
      AMD64_MACOSX_CLANG: zsv-amd64-macosx-clang
      AMD64_FREEBSD_GCC: zsv-amd64-freebsd-gcc
      ARTIFACT_RETENTION_DAYS: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install MinGW cross-compiler on Linux
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install -y mingw-w64

    # --- Build ---

    - name: Build on Linux (${{ env.AMD64_LINUX_GCC }})
      if: runner.os == 'Linux'
      env:
        PREFIX: ${{ env.AMD64_LINUX_GCC }}
        CC: gcc
        MAKE: make
        TESTS: true
      shell: bash
      run: ./scripts/ci-build.sh

    - name: Build on Linux (${{ env.AMD64_LINUX_CLANG }})
      if: runner.os == 'Linux'
      env:
        PREFIX: ${{ env.AMD64_LINUX_CLANG }}
        CC: clang
        MAKE: make
        TESTS: false
      shell: bash
      run: ./scripts/ci-build.sh

    - name: Build on Linux (${{ env.AMD64_WINDOWS_MINGW }})
      if: runner.os == 'Linux'
      env:
        PREFIX: ${{ env.AMD64_WINDOWS_MINGW }}
        CC: x86_64-w64-mingw32-gcc
        MAKE: make
        TESTS: false
      shell: bash
      run: ./scripts/ci-build.sh

    - name: Build on macOS (${{ env.AMD64_MACOSX_CLANG }})
      if: runner.os == 'macOS'
      env:
        PREFIX: ${{ env.AMD64_MACOSX_CLANG }}
        CC: clang
        MAKE: make
        TESTS: false
      shell: bash
      run: |
        # coreutils required for realpath
        brew install coreutils tree
        ./scripts/ci-build.sh

    - name: Build on macOS (${{ env.AMD64_FREEBSD_GCC }})
      if: runner.os == 'macOS'
      env:
        PREFIX: ${{ env.AMD64_FREEBSD_GCC }}
        CC: gcc
        MAKE: gmake
        TESTS: false
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'PREFIX CC MAKE TESTS'
        usesh: true
        prepare: pkg install -y tree zip gmake lang/gcc
        run: ./scripts/ci-build.sh

    # --- Upload ---

    - name: Upload (${{ env.AMD64_LINUX_GCC }}.zip)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AMD64_LINUX_GCC }}.zip
        path: ${{ env.AMD64_LINUX_GCC }}.zip
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error

    - name: Upload (${{ env.AMD64_LINUX_CLANG }}.zip)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AMD64_LINUX_CLANG }}.zip
        path: ${{ env.AMD64_LINUX_CLANG }}.zip
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error

    - name: Upload (${{ env.AMD64_WINDOWS_MINGW }}.zip)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AMD64_WINDOWS_MINGW }}.zip
        path: ${{ env.AMD64_WINDOWS_MINGW }}.zip
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error

    - name: Upload (${{ env.AMD64_MACOSX_CLANG }}.zip)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AMD64_MACOSX_CLANG }}.zip
        path: ${{ env.AMD64_MACOSX_CLANG }}.zip
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error

    - name: Upload (${{ env.AMD64_FREEBSD_GCC }}.zip)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AMD64_FREEBSD_GCC }}.zip
        path: ${{ env.AMD64_FREEBSD_GCC }}.zip
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ env.AMD64_LINUX_GCC }}.zip
          ${{ env.AMD64_LINUX_CLANG }}.zip
          ${{ env.AMD64_WINDOWS_MINGW }}.zip
          ${{ env.AMD64_MACOSX_CLANG }}.zip
          ${{ env.AMD64_FREEBSD_GCC }}.zip
