name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15

    runs-on: ${{ matrix.os }}
    
    env:
      PREFIX: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build (Linux/gcc)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Building with gcc"
        gcc --version
        CC=gcc ./configure --prefix=$PREFIX
        make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with gcc successfully!"

    - name: Build (Linux/clang)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        rm -rf $PREFIX
        echo "Building with clang"
        clang --version
        CC=clang ./configure --prefix=$PREFIX
        make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"

    - name: Build (Linux/mingw)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        rm -rf $PREFIX
        sudo apt install -y mingw-w64
        echo "Building with mingw"
        x86_64-w64-mingw32-gcc --version
        CC=x86_64-w64-mingw32-gcc ./configure --prefix=$PREFIX
        make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with mingw successfully!"
        echo "--- [DONE] ---"

    - name: Build (macOS - clang)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # coreutils required for realpath
        brew install coreutils tree
        echo "Building with clang"
        clang --version
        CC=clang ./configure --prefix=$PREFIX
        make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"

    - name: Build (macOS - FreeBSD/gcc)
      if: runner.os == 'macOS'
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'PREFIX'
        usesh: true
        prepare: pkg install -y tree gmake lang/gcc
        run: |
          set -e
          rm -rf $PREFIX
          echo "Building with gcc"
          gcc --version
          CC=gcc ./configure --prefix=$PREFIX
          gmake install
          tree -h $PREFIX/{bin,include,lib}
          echo "Built with gcc successfully!"
