name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build (Linux - gcc and clang)
      if: runner.os == 'Linux'
      run: |
        ./configure --prefix=build
        # gcc
        echo "Building with gcc"
        CC=gcc make install
        # clang
        echo "Building with clang"
        CC=clang make install
        echo "Built successfully!"

    - name: Build (macOS - clang)
      if: runner.os == 'macOS'
      run: |
        brew install coreutils
        ./configure --prefix=build
        echo "Building with clang"
        CC=clang make install
        echo "Built successfully!"
