name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}
    
    env:
      PREFIX: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      shell: bash
      run: ./configure --prefix=$PREFIX

    - name: Build (Linux - gcc and clang)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # gcc
        echo "Building with gcc"
        gcc --version
        CC=gcc make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with gcc successfully!"
        # clang
        rm -rf $PREFIX
        echo "Building with clang"
        clang --version
        CC=clang make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"

    - name: Build (macOS - clang)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # coreutils required for realpath
        brew install coreutils tree
        echo "Building with clang"
        clang --version
        CC=clang make install
        tree -h $PREFIX/{bin,include,lib}
        echo "Built with clang successfully!"
        echo "--- [DONE] ---"

    - name: Build (FreeBSD - gcc)
      if: runner.os == 'macOS'
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'PREFIX'
        usesh: true
        prepare: pkg install -y lang/gcc49
        run: |
          freebsd-version
          echo "Building with gcc"
          gcc --version
          CC=gcc make install
          tree -h $PREFIX/{bin,include,lib}
          echo "Built with gcc successfully!"

    # - name: Build (Windows - mingw)
    #   if: runner.os == 'Windows'
    #   shell: bash
    #   run: |
    #     echo "Building with mingw"
    #     make install
    #     tree -h $PREFIX/{bin,include,lib}
    #     echo "Built with mingw successfully!"
    #     echo "--- [DONE] ---"
